### PR TITLE
Add "Reacting to Firestore changes with GCF and EventArc"

### PR DESCRIPTION
**Pull request by thatfiredev**
Adding the sample code for the new Firebase codealong

### CODE REVIEW

**Review by ChinoJones — APPROVED** [review]
https://youtu.be/xvFZjo5PgG0?si=2HwQgSHmqv6vnpcp

**Review by peterfriese — CHANGES_REQUESTED** [review]
Code LGTM.

Is this part of a series / are we expecting to see more of these? We have a folder for `fundamentals`. If this is not for a Fundamental, consider creating a top-level folder for the series it belongs to, or the type of content.

**Review by peterfriese — CHANGES_REQUESTED** [review]
Code LGTM.

Is this part of a series / are we expecting to see more of these? We have a folder for `fundamentals`. If this is not for a Fundamental, consider creating a top-level folder for the series it belongs to, or the type of content.

**Comment by thatfiredev** [comment]
Leaving a comment for future reference: I chatted with Peter offline, we have decided creating a top-level `codealongs` folder for this series. We'll create one once we have more videos in the pipeline.

**Pull request merged**
